### ISSUE TITLE
Task1: Rendering notebooks

### ISSUE THREAD

**Issue by grst** [scverse/scverse-tutorials#1]
Hi @scverse/core-devs, 

I think we all agree that (in one form or the other) our tutorials will be based on jupyter notebooks. 

But how do we render them? I see the following requirements
 * They should be available all from one nice looking website
 * There should be some sort of interactivity (i.e. the possibility to execute the notebooks online) 
 * Ideally, we have the option to optionally execute notebooks by the CI (but it should be also possible to use an executed `.ipynb` file, as some of the notebooks might be too computationally expensive) 

Possible solutions: 
 * [jupyterbook]() (@Zethson)
 * sphinx with [myst-nb](https://myst-nb.readthedocs.io/en/latest/) (we use that in the cookiecutter template already)

For interactivity the notebooks can be linked to various online services like binder or google colab. For binder it's easier to declare dependencies as a yml file, but google colab has access to GPU which is particularly useful for scvi-tools. 
See also https://sphinx-book-theme.readthedocs.io/en/stable/launch.html#launch-buttons-for-interactivity

There's also [thebe](https://sphinx-book-theme.readthedocs.io/en/stable/launch.html#live-code-cells-with-thebe) which would allow to run code cells directly within sphinx. I didn't like their demo too much though, and I also don't see a clear advantage over opening binder/colab. 

### Hosting
If we go for sphinx, we could consider readthedocs. But probably building our own CI gives us more flexibility and resources for executing the notebooks and we can simply push sphinx/jupyterbook to github pages. The only downside is that it is hard to have multiple versions of the documentation (but not sure we need that for the tutorials). 

WDYT?

**Comment by Zethson** [comment]
Thank you very much for writing this up.

> They should be available all from one nice looking website

Just to ensure that we are on the same page. We are only talking about scverse CORE package tutorials here, right? Or do you think that scverse validated ecosystem packages should also be allowed to have a tutorial or two here?

> There should be some sort of interactivity (i.e. the possibility to execute the notebooks online)

Yes, please. We should design everything with this in mind. I think that we'll need GPU support though, right @adamgayoso ?

> If we go for sphinx, we could consider readthedocs. But probably building our own CI gives us more flexibility and resources for executing the notebooks and we can simply push sphinx/jupyterbook to github pages. The only downside is that it is hard to have multiple versions of the documentation (but not sure we need that for the tutorials).

I'd prefer having full control. Multiple versions of the tutorials are certainly useful, but I think that we want to encourage people to work with the latest versions at any point anyways. If we support multiple rendered versions of the tutorials we might also have to provide support for their code. I'd strongly want to avoid this.

My experiences with Jupyterbook are pretty good. As always, there are some things that you wish you could customize etc, but the out of the box setup is very good.

**Comment by ivirshup** [comment]
> So it seems to come down to personal perference if we want to use jupyterbook or sphinx.

Jupyterbook is just a configuration of sphinx right? But very configured to make something that looks like a book?

While I think what we want overlaps a lot with Jupyter-book, I don't think we're making a book. Instead, I think we will just use a bunch of the jupyter-book components.

**Comment by ivirshup** [comment]
Split out discussion on interactivity to #3

**Comment by ivirshup** [comment]
I would also like to point to this related discussion from the pangeo community: https://discourse.pangeo.io/t/statement-of-need-integrating-jupyterbook-and-jupyterhubs-via-ci/2705

### Using the interactive environment for building

One cool idea from that space is using the environment where users can interact with the notebooks for building them.

This seems like it could be possible with `binderbot` and may even have actions available through [project pythia](https://github.com/ProjectPythiaCookbooks/cookbook-actions/blob/main/.github/workflows/build-book.yaml)

### Open contribution

> IMO there is room for cross-package tutorials here that also use ecosystem tutorials (e.g. decoupler functional analysis combined with scanpy).
>
> We could also link to/highlight ecosystem tutorials in the future. This would go hand in hand with what I wrote on Zulip about making the ecosystem "first-class".

The model discussed for pangeo is very much open contribution. I like this, especially since it does not put maintenance of the tutorials strictly on the core team.

**Comment by adamgayoso** [comment]
I think jupyter book makes sense for this project (and yes I see it as a specific usage of sphinx)

**Comment by adamgayoso** [comment]
By the way, this quant econ book has really nice css, etc

https://python.quantecon.org/heavy_tails.html

**Comment by adamgayoso** [comment]
Yeah it's basically as easy to try as installing the package and doing

```
sphinx:
    config:
        html_theme: quantecon_book_theme
```

**Comment by grst** [comment]
> By the way, this quant econ book has really nice css, etc

Not sure I like this better than the default jupyter book theme... The mix of serif and non-serif fonts is ugly. 

> One cool idea from that space is using the environment where users can interact with the notebooks for building them.

This seems like a good idea to me! Also ensures that the notebooks actually run there and not only on github actions. 

Any preference of (sphinx + jupyterbook theme) vs jupyter book? I feel with using sphinx directly we might have more flexibility in the long run, but jupyterbook does seem to have sensible defaults :shrug:

**Comment by grst** [comment]
So the solution I discussed with @Zethson looks as follows:

 * define a conda env for each notebook 
 * spawn a CI process for each notebook and execute it. Upload the executed ipynb as an artifact. 
 * retrieve the executed ipynbs and build the sphinx website. 

In principle I like @ivirshup's idea of using binder for executing the notebooks. However IMO this makes only sense if we move to a custom binderhub instance with more resources.

**Comment by grst** [comment]
Current solution: 
 * Github actions build notebooks using jupyter-cache. 
 * If there were changes, make a commit to the same branch
 * This triggers another RTD build. 

If we ever have custom AWS runners, this can run in one and we'll have parallelization and GPU support.
