### ISSUE TITLE
Overview page

### ISSUE THREAD

**Issue by grst** [scverse/scverse-tutorials#13]
Would be nice to have a landing page that shows previews of the tutorials. 

Maybe this is possible with sphinx-gallery?

**Comment by grst** [comment]
https://sphinx-gallery.github.io/stable/auto_examples/index.html

**Comment by Zethson** [comment]
Yes, surely possible with sphinx-gallery. Have a look at https://github.com/theislab/ehrapy/issues/411 and the mentioned issues though, please.

**Comment by grst** [comment]
In the end, the overview page was implemented with [sphinx-design](https://sphinx-design.readthedocs.io/en/latest/). 
All the building blocks are there, just need to finalize the structure once all tutorials are online.
