### ISSUE TITLE
Update basic clustering tutorial to be in sync with scanpy 1.10

### ISSUE THREAD

**Issue by ivirshup** [scverse/scverse-tutorials#153]
Scanpy now features a cut down version of the basic plotting tutorial hosted here, which shows all the steps that only rely on scanpy.

https://scanpy.readthedocs.io/en/stable/tutorials/basics/clustering.html

While updating this, I made some modification that take advantage of new scanpy features. We should update the version here to be in sync.

**Comment by ilan-gold** [comment]
Blocked by myst parser issue, slow response
