### ISSUE TITLE
This is currently a package

### ISSUE THREAD

**Issue by ivirshup** [scverse/scverse-tutorials#18]
This repository isn't really a package, but is set up as one.

Can we change that?

We would need to figure out how to do metadata and dependencies, but surely this is a thing jupyter book can do.

**Comment by grst** [comment]
What if we had some helper functions shared across tutorials? e.g. ` setup_conda_for_colab()` or `set_appropriate_logging_verbosity_for_tutorials()`?

**Comment by grst** [comment]
I think this is ok as is. @flying-sheep added some metadata to the pyproject.toml in #129 that e.g. prevents it from being published as a package.
