### ISSUE TITLE
Do all tutorial notebooks have to live here?

### ISSUE THREAD

**Issue by ivirshup** [scverse/scverse-tutorials#2]
Do we want to have all tutorial notebooks live here, or is it okay to refer to notebooks here that live in other places?

For example, it makes sense that anndata has a "intro to anndata" tutorial, but a comprehensive set of tutorials should include that too.

Some ways we could include tutorials that live elsewhere:

* Vendor a copy here
* Link out
* Grab those notebooks as part of the build process

Vendoring and grabbing notebooks have the downside of requiring compatibility. E.g. if someone uses a fancy sphinx plugin for their notebooks, they may not render well here.

(As discussed a little with @Zethson IRL)

**Comment by adamgayoso** [comment]
Linking back and forth between this and main package docs doesn't seem so bad to me, as for users there are only two places to look.

Having this be the only place for package tutorials is not ideal for us as the release cycle might not match our package release cycle. However, if we could figure out that problem, then I see an ideal situation as the packages hosting examples (like squidpy) and more vignette style tutorials go here.

**Comment by grst** [comment]
> the release cycle might not match our package release cycle

I'm not even sure we need a release cycle for the tutorials. Just merge a PR into main and you're live!

**Comment by ivirshup** [comment]
>  However, if we could figure out that problem, then I see an ideal situation as the packages hosting examples (like squidpy) and more vignette style tutorials go here.

So this is should have the capability to both link in tutorials from packages, and have local tutorials.

I would like to think about what sort of materials fit well here, that don't in specific packages. I'm thinking tutorials that are more related to data resources or a broad topic not captured by a single package. So, sources could include specific papers or benchmarks?

**Comment by adamgayoso** [comment]
> I'm not even sure we need a release cycle for the tutorials. 

For our users it's been helpful to look at previous versions of the tutorials as we've made API changes/tutorial changes

**Comment by grst** [comment]
When my attempt to switch to RTD (#23) is successful, we'll have versioning for free. 

We could go with a simple CalVer approach then.

**Comment by ivirshup** [comment]
Can we close this? I think we've decided we want to have notebooks that don't live in this repo. Now it's a discussion of solution, where I think we're going with https://github.com/scverse/scverse-tutorials/issues/6 for now.
