### ISSUE TITLE
Plotting cookbook

### ISSUE THREAD

**Issue by grst** [scverse/scverse-tutorials#25]
Should we have some general tips for saving figures and adjusting figure dimensions? 

I'm thinking of things like 

```python
with plt.rc_context({"figure.figsize": (5, 8)}):
    fig = sc.pl.umap(adata, "CD8A", return_fig = True)
    fig.savefig("umap_cd8a.pdf", dpi=600)
```

to actually save figures in publication-ready quality.

**Comment by grst** [comment]
@ivirshup, WDYT?

**Comment by ivirshup** [comment]
cc: @Hrovatin 

This ended at:

* https://github.com/scverse/scanpy-tutorials/pull/61

But should maybe get linked in here
