### ISSUE TITLE
Task 4: Link tutorials from other sources

### ISSUE THREAD

**Issue by grst** [scverse/scverse-tutorials#6]
We do not want to compete with Lukas’ [single-cell-best-practice book](https://www.sc-best-practices.org/). Instead, we can link to relevant sections / include the relevant notebooks directly in our tutorials page

Some modality-specific tutorials (scirpy, squidpy, mudata) could be included directly.

Tasks as defined by Lukas:

- [ ] Discuss how the redundancy between the book and the current scverse core packages documentation can be reduced (biggest violator by far -> https://www.sc-best-practices.org/introduction/analysis_tools.html). Is there a way to concatenate jupyter notebooks with https://github.com/jbn/nbmerge?
- [ ] How/when could we link to high quality scverse ecosystem packages? What are the criteria? Should we render their notebooks directly on the scverse site?
- [ ] When would it make sense to link to specific book chapters in the current/new scverse core packages' documentation?

**Comment by Zethson** [comment]
Idea:

We can add a pre-build hook (or just edit the Makefile) which downloads the latest versions of the official AnnData/MuData etc notebooks and then we concatenate them with nbmerge to finally serve them.

**Comment by grst** [comment]
Thanks for putting together the inclusion criteria! I think this is really useful when we are approached by ecosystem package maintainers if we can include their tutorials. 

For now, more concretely, what is the list of tutorials that we want to link from the site initially?

**Comment by Zethson** [comment]
I want to write this up into a proper doc + will then add this information. It's on my TODO list.

**Comment by Zethson** [comment]
@grst so I didn't want to create another doc yet after all because stuff gets scattered.

1. I added some first suggested packages whose tutorials I could see being added. We can easily brainstorm and add more
2. Where should this stuff end up and be formalized? Some doc in the governance channel?
3. Everything book related is probably easier to track in the book repository. I can then still reach out to people here if required.

**Comment by grst** [comment]
Superseded by #58 and #53
